bucket/models.py
from bucket import db, login
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


class Product(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String(64), unique=True)
	category = db.Column(db.String(64))
	color = db.Column(db.String(64))
	stock = db.Column(db.Integer)
	selling_price = db.Column(db.Float)
	
	def __repr__(self):
		return f'Product {self.name}'

class User(UserMixin, db.Model):
	id = db.Column(db.Integer, primary_key=True)
	email = db.Column(db.String(128), index=True, unique=True)
	password_hash = db.Column(db.String(128))

	def __repr__(self):
		return f'User {self.email}'

	def set_password(self, password):
		self.password_hash = generate_password_hash(password)

	def check_password(self, password):
		return check_password_hash(self.password_hash, password)


@login.user_loader
def load_user(id):
	return User.query.get(int(id))

bucket/admin/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, RadioField, SubmitField, SelectField
from wtforms.validators import ValidationError, DataRequired


class StockForm(FlaskForm):
	name = SelectField('Name of Item', choices=[('hat', 'Bucket Hat'), ('pants', 'Jeans')], validators=[DataRequired()])
	operation = RadioField('Operation', choices=[('add', 'Add'), ('subtract', 'Subtract'), ('reset', 'Reset')], validators=[DataRequired()])
	number = IntegerField('Amount of Stock', validators=[DataRequired()])
	submit = SubmitField('Change Stock Value')

class ProductForm(FlaskForm):
	name = StringField('Name of Product', validators=[DataRequired()])
	stock = IntegerField('Amount of Stock', validators=[DataRequired()])
	category = SelectField('')

bucket/store/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, SubmitField, StringField, IntegerField

class CheckoutForm(FlaskForm):
	pass
	

bucket/__init__.py
import os
from flask import Flask
from config import Config
from flask_debugtoolbar import DebugToolbarExtension
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

toolbar = DebugToolbarExtension()
db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()


def create_app(test_config=None):
	# create an configure the app
	app = Flask(__name__, instance_relative_config=True)
	app.debug = True
	app.config.from_object(Config)

	toolbar.init_app(app)
	db.init_app(app)
	migrate.init_app(app, db)
	login.init_app(app)

	from . import main
	app.register_blueprint(main.bp)

	from . import store
	app.register_blueprint(store.bp)

	from . import auth
	app.register_blueprint(auth.bp)

	from . import admin
	app.register_blueprint(admin.bp)

	login.login_view = 'auth.login'

	return app

from . import models

bucket/admin/__init__.py
from flask import Blueprint

bp = Blueprint('admin', __name__)

from . import routes

bucket/admin/routes.py
from bucket import db
from bucket.models import Product
from .forms import ProductForm
from flask import render_template, redirect, url_for, flash
from flask_login import current_user
from . import bp

@bp.route('/admin')
@bp.route('/admin/navigate')
def navigate():
	return render_template('admin/navigate.html')

@bp.route('/admin/product', methods=['GET', 'POST'])
def product():
	form = ProductForm()
	return render_template('admin/product.html', form=form)

bucket/main.py
from flask import Blueprint, render_template, url_for

bp = Blueprint('main', __name__)


@bp.route('/home')
@bp.route('/index')
@bp.route('/')
def home():
	return render_template('main/home.html')


@bp.route('/contact')
def contact():
	return render_template('main/contact.html')

bucket/store/__init__.py
from flask import Blueprint

bp = Blueprint('store', __name__)

from . import routes

bucket/store/routes.py
from bucket import db
from bucket.models import Product
from .forms import CheckoutForm
from flask import render_template, redirect, url_for, flash
from flask_login import current_user
from . import bp

@bp.route('/products')
def products():
	pass

bucket/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %} - The Bucket</title>
	<link rel='stylesheet' href='{{ url_for("static", filename="css/stylesheet.css") }}'>
	<script src='{{ url_for("static", filename="js/script.js") }}'></script>
</head>
{% block body %}{% endblock %}
</html>

bucket/templates/base_header.html
{% extends 'base.html' %}
{% block body %}
	<body>
		<header>
			<div class='image-container'>
				<img src='{{ url_for("static", filename="img/logo.png") }}' alt='The Bucket Logo'>
			</div>
			<div class='button-container'>
				<div class='menu-button' onclick='hamburgerClick()'>
					<div class='bar1'></div>
					<div class='bar2'></div>
					<div class='bar3'></div>
				</div>
			</div>
		</header>
		<div class='menu'>
			<ul>
				<li><a href='{{ url_for("main.home") }}'>Home</a></li>
				<li><a href='{{ url_for("main.contact") }}'>Contact Us</a></li>
			</ul>
		</div>
		{% block content %}{% endblock %}
	</body>
{% endblock %}

bucket/templates/main/contact.html
{% extends 'base_header.html' %} 
{% block content %}
	<div class='contact'>
		<h1>Contact Us</h1>
		<h2>Email</h2>
		<p>info@thebucket.store</p>
		<h2>Social Media</h2>
		<p>Instagram</p>
		<p>Facebook</p>
	</div>
{% endblock content %}

bucket/templates/main/home.html
{% extends 'base_header.html' %}

{% block title %}Home{% endblock %}

{% block content %}
	<div class='background'>
		<img src='{{ url_for("static", filename="img/background.jpg") }}' alt='Bucket hats and beanies' class='bg-img'>
		<a href='{{ url_for("store.products") }}' class='bg-button'>View Products</a>
	</div>
{% endblock %}